version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm i
      - run:
          name: Run Unit run_tests
          command: |
            npm test
      # - store_test_results:
      #     path: test-results
      # - store_artifacts:
      #     path: test-result 
workflows:
  build-tests:
    jobs:
      - run_tests
